### ISSUE TITLE
pythia-12b checkpoints missing on HuggingFace for step4000 and step32000

### ISSUE THREAD

**Issue by byungdoh** [EleutherAI/pythia#107]
Dear EleutherAI team,

I've noticed that the checkpoints for the pythia-12b model at [step4000](https://huggingface.co/EleutherAI/pythia-12b/tree/step4000) and [step32000](https://huggingface.co/EleutherAI/pythia-12b/tree/step32000) are currently missing on HuggingFace (and maybe some others, but these two were what I found). Could you take a look and upload the missing files if possible?

Thanks!

**Comment by haileyschoelkopf** [comment]
Hi @byungdoh , I've uploaded those two missing checkpoints, sorry about this! I've started to work my way through checking the 12b and 6.9b branches more rigorously, and will upload checkpoints if I see any more missing! 

Sorry for the trouble!

**Comment by byungdoh** [comment]
Awesome, thanks so much!
