### ISSUE TITLE
Host pythia suite

### ISSUE THREAD

**Issue by haileyschoelkopf** [EleutherAI/pythia#12]
We need to upload all model checkpoints to be hosted somewhere for researchers to access them.

Final checkpoints should go on the HF hub. Intermediate ckpts pending

**Comment by StellaAthena** [comment]
Intermediate checkpoints will now also be hosted on the HF Hub!

**Comment by haileyschoelkopf** [comment]
Woo! closing as the last of the uploads is in progress.
