### ISSUE TITLE
Deduplicated Pile dataset with Domain Attribution

### ISSUE THREAD

**Issue by michaelduan8** [EleutherAI/pythia#137]
Hi there!

I was wondering if there was a way to reproduce [this dataset](https://huggingface.co/datasets/EleutherAI/the_pile_deduplicated) with domain attribution (determining which Pile subdomain a given document comes from) or if the existing dataset at that link could be updated with domain metadata?

Thanks!

**Comment by ilyalasy** [comment]
Hi @michaelduan8, have you solved that issue?
I am interested in mapping indexes from deduped Pile to domains as well.
