### ISSUE TITLE
General zero and few-shot evaluations on model suite

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/pythia#16]
Collect zero-shot and 5-shot performance on the Pythia model suite across a selected subset of checkpoints over time. 

Tasks:

- [ ] MMLU (57 tasks)
- [ ] BLiMP
- [ ] PiQA
- [ ] SciQ
- [ ] Lambada
- [ ] Wikitext
- [ ] Winogrande
- [ ] WSC
- [ ] Arc-challenge and ARC-easy
- [ ] Logiqa

**Comment by haileyschoelkopf** [comment]
@Kyle1668 this is the issue, I can't assign you for some reason. Let's track statuses in the table in the Pythia README! (maybe in an `evals` branch if needed).

**Comment by StellaAthena** [comment]
@haileyschoelkopf you can’t assign him because he’s not in the EAI GitHub group. I’ll send him an invite

**Comment by Kyle1668** [comment]
Sounds good y'all! I've created a branch to track what I'm up to. https://github.com/EleutherAI/pythia/blob/8f4cb1004dab7fb33c3f789fb0b82cf6477a4dee/README.md
