### ISSUE TITLE
Does memorization in small models predict memorization in large models?

### ISSUE THREAD

**Issue by uSaiPrashanth** [EleutherAI/pythia#19]

**Comment by StellaAthena** [comment]
We currently have the following correlation heat-map which indicates that the answer is "no." We should probably also make confusion matrices for the classifier that takes a small model and predicts memorization by the 13B model by assuming it is the same as the small model.

![Image](https://user-images.githubusercontent.com/15899312/205145917-80cb56e8-0aac-448c-b01c-682f7e113d22.png)

**Comment by lintangsutawika** [comment]
There seems to be a trend where (but weak) where the larger the model, the more it is able to predict if a sequence from 13B is memorized or not.
![image](https://user-images.githubusercontent.com/5774558/207216411-8b9ccba6-a6fb-446d-a4a4-94c60ec4a2ff.png)
![image](https://user-images.githubusercontent.com/5774558/207216536-48a3339f-1be7-4c18-9c04-05c7796cc872.png)
![image](https://user-images.githubusercontent.com/5774558/207216548-51adeba3-08dd-4781-9684-f7cc8ca6528a.png)
![image](https://user-images.githubusercontent.com/5774558/207216559-49e09bea-00c0-46fe-ace1-33f3f782bbdc.png)
![image](https://user-images.githubusercontent.com/5774558/207216570-b7105771-5085-4f2a-a3ed-de6b5288c40e.png)
![image](https://user-images.githubusercontent.com/5774558/207216583-537ba797-c996-4d84-85a3-00bf497429bc.png)
![image](https://user-images.githubusercontent.com/5774558/207216598-5d3ab3d2-e29a-48d7-af56-c5c6da83e8e1.png)
![image](https://user-images.githubusercontent.com/5774558/207216608-0703d8bf-f12a-40c5-bfb0-4863f686cc99.png)

**Comment by StellaAthena** [comment]
The same comments about follow-ups I made on https://github.com/EleutherAI/pythia/issues/29 apply here. The conclusions are different but the methodologies are the same.
