### ISSUE TITLE
Survival model analysis

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/pythia#20]
[Survival analysis](https://scikit-survival.readthedocs.io/en/stable/user_guide/00-introduction.html) is a potential model for understanding whether the fact that a model has memorized a string at time t is likely to continue to have that string memorized or not.

**Comment by Kyle1668** [comment]
With the caveat that I haven't done anything like this before, I'm interested in taking this on.

**Comment by StellaAthena** [comment]
@Quentin-Anthony @ShivanshuPurohit would either of you be interested in and have the bandwidth to work on this over the next week? It shouldn’t be more than a couple hours of work I expect.
