### ISSUE TITLE
Host Deduped Pile raw jsonls

### ISSUE THREAD

**Issue by haileyschoelkopf** [EleutherAI/pythia#27]
I don't think that the deduped Pile raw text data is hosted anywhere--I couldn't find it on the eye. Even if we don't host the deduped Pile `.bin` and `.idx` files somewhere, we definitely need to host the raw deduped Pile data to make these experiments replicable.

**Comment by aflah02** [comment]
@haileyschoelkopf Thanks for the great work on this repo! Is there any ETA for the Pile dataset hosting? Would be really helpful for some analysis

**Comment by haileyschoelkopf** [comment]
Hi, thanks for the interest!

I've uploaded the deduplicated Pile in Parquet format on HF datasets, which may be helpful:
[https://huggingface.co/datasets/EleutherAI/the_pile_deduplicated](https://huggingface.co/datasets/EleutherAI/the_pile_deduplicated)

I'll try to upload the JSONLs today, running into issues with filesize for our .bin and .idx files from NeoX.

Please let me know if you have any questions about replicating data ordering in training. We'll have something up on replicating the data seen by the model very soon!

**Comment by aflah02** [comment]
Thanks a ton!

**Comment by haileyschoelkopf** [comment]
https://huggingface.co/datasets/EleutherAI/raw_deduplicated_pile BTW, all the deduped Pile jsonl files are here now :)

**Comment by aflah02** [comment]
Thanks!!
