### ISSUE TITLE
Does early memorization predict late memorization?

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/pythia#29]
We currently have the following correlation heat-map which indicates that the answer is "yes." We should probably also make confusion matrices for the classifier that takes a model and predicts memorization by the fully trained model by assuming it is the same as the 23M sequence checkpoint.

![Image](https://user-images.githubusercontent.com/15899312/205146532-3dbf41e2-1569-4b73-97df-9c6737038172.png)

**Comment by lintangsutawika** [comment]
The correlation looks strong. This is for 13B model.

![image](https://user-images.githubusercontent.com/5774558/207222386-f315c7fb-0d5d-4702-9296-c9f300b266df.png)
![image](https://user-images.githubusercontent.com/5774558/207222423-b7ad57be-32ff-4b03-99ce-10da68499268.png)
![image](https://user-images.githubusercontent.com/5774558/207222437-14cf0e6f-3c57-41d0-85ec-92b2d90b7fc8.png)
![image](https://user-images.githubusercontent.com/5774558/207222445-d2e40f9c-d22c-4916-b674-84e22c4104b2.png)
![image](https://user-images.githubusercontent.com/5774558/207222449-60f937dd-9ac3-4a9a-b817-c95832e4085e.png)
![image](https://user-images.githubusercontent.com/5774558/207222462-e6cfb3c1-c5c4-4fba-b471-8cc54fcd474f.png)
![image](https://user-images.githubusercontent.com/5774558/207222470-0a66e845-2380-498c-ae2d-5f5481f2a945.png)

**Comment by lintangsutawika** [comment]
The trend is consistent in small models (19M)
![image](https://user-images.githubusercontent.com/5774558/207222961-75ce6e6f-6077-4983-bc24-2336c3f309ff.png)
![image](https://user-images.githubusercontent.com/5774558/207222966-f71dd5b8-e741-46f2-9564-9ed0038ff20f.png)
![image](https://user-images.githubusercontent.com/5774558/207222974-d757a468-a3e5-45eb-a565-14740e5f1e9b.png)
![image](https://user-images.githubusercontent.com/5774558/207222983-54d47d00-5683-4095-bde9-5fb423bc288d.png)
![image](https://user-images.githubusercontent.com/5774558/207222990-693cd66d-75a2-419d-905e-19c5b7d31557.png)
![image](https://user-images.githubusercontent.com/5774558/207222995-0d244c1e-1ea2-4cd5-b010-513bb97b86a4.png)
![image](https://user-images.githubusercontent.com/5774558/207223001-6abb1929-8eb8-4c17-baaf-318ac40fb570.png)

**Comment by StellaAthena** [comment]
@lintangsutawika very interesting! It looks like the change between checkpoints is mostly confined to FP cell.. the TN and FN numbers are rather consistent across the course of training (until the end, where incorrect judgements are impossible).

One potential next step is to plot the TP, FP, and FN rates as a function of the number of steps the checkpoint has been trained for. My intuition is that we should plot this with a logarithm on the x-axis (I know this will make it look funky), maybe do it both with and without a log and see what they look like? 

Another analysis worth doing is looking at the *consistency* across checkpoints. Obviously the final checkpoint gets all predictions correct, but once points get categorized correctly do they remain correctly categorized throughout the remaining checkpoints? I guess what I have in mind here is a markov model for how individual predictions move around the four states over the course of training. Does that make sense?

This is a minor thing, but I’m used to these matrices being laid out slightly differently, as shown in the below image. Would you mind reorienting them? It’s messing with my head 
![89902D94-A797-46F6-97F0-CF51B15B2D28](https://user-images.githubusercontent.com/15899312/207227179-3aa7630d-f88a-4eba-8054-71a187d2f4e6.png)

**Comment by lintangsutawika** [comment]
No problem.
![image](https://user-images.githubusercontent.com/5774558/207265125-b4670bfa-3f64-438e-95ca-2abdc3a8edd2.png)
![image](https://user-images.githubusercontent.com/5774558/207265144-52a6ac82-d132-40ea-b853-94e202e3ed7e.png)
![image](https://user-images.githubusercontent.com/5774558/207265156-1d8972b7-2d4f-436c-817d-c934ec868d68.png)
![image](https://user-images.githubusercontent.com/5774558/207265164-7f5d7f1b-bee6-4399-8cc1-6eba75de90f9.png)
![image](https://user-images.githubusercontent.com/5774558/207265176-ff142058-a036-44de-886b-798a0e1ade10.png)
![image](https://user-images.githubusercontent.com/5774558/207265188-f6d4938c-751b-4455-9207-ba4f9592933c.png)
![image](https://user-images.githubusercontent.com/5774558/207265197-0c3d662c-b184-4d15-a117-67bbd85a6d4f.png)

**Comment by lintangsutawika** [comment]
Preliminary graphs through steps for all model sizes until before 146M.

TPR
![image](https://user-images.githubusercontent.com/5774558/207360543-4e2650c6-7eae-4225-9f3c-3002687ce5f9.png)
 
 FPR
 
![image](https://user-images.githubusercontent.com/5774558/207360957-f74d4d52-72c9-4a21-bd9c-6b6c870adee9.png)

 
 FNR
 
![image](https://user-images.githubusercontent.com/5774558/207361354-37c5de96-ba11-4d84-9b82-eb103057a994.png)

**Comment by lintangsutawika** [comment]
Also, I tried graphing the number of lines memorized through checkpoints for each model.

It looks like there is a linear growth for all models and that the rate of growth increases as the model size gets larger.

![image](https://user-images.githubusercontent.com/5774558/207624748-fd823438-bd8a-4821-b9db-d6d41cb2bf34.png)

**Comment by StellaAthena** [comment]
@lintangsutawika This is great work, and I think with a little addition design iteration will be an important component of the memorization paper. Unfortunately the raw underlying memorization data was erroneous, but @uSaiPrashanth is working on fixing that and should have new data by Jan 1. Have you had a chance to read the WIP paper draft?

I’m hoping we can package these results and deliver a paper to ICML (deadline Jan 26). I think this is a realistic but non-trivial deadline to make, and that we have really compelling results so far.

Where is the code you’ve been working with? Is it on a branch / fork somewhere, in a Jupyter Notebook, or what?

**Comment by lintangsutawika** [comment]
I have the code in Jupyter Notebook that I copied from Sai's. I can rerun and adjust the graphs for the paper. 

I haven't read the paper draft. I've reached out to Sai for help.

**Comment by StellaAthena** [comment]
Great. Can you upload that notebook to `analysis/memorization`

**Comment by lintangsutawika** [comment]
What happens to points that are forgotten? Tracking all the points that were memorized in the first checkpoints, the all model sizes tend to forget what they memorized earlier. Connecting this to above graph, where the number of memorization increases, this probably means that the ones memorized later are new points and that the ones memorized earlier have a slight tendency to be forgotten. 
![image](https://user-images.githubusercontent.com/5774558/210300090-351939f3-9e4e-4278-abe4-c9abe5b5ca3a.png)

**Comment by lintangsutawika** [comment]
Added notebook in a PR for now.
https://github.com/EleutherAI/pythia/pull/50
