### ISSUE TITLE
Fix currently uploaded eval-harness numbers for 1.3B ; 6.7B

### ISSUE THREAD

**Issue by haileyschoelkopf** [EleutherAI/pythia#37]
Currently some of the 0 and 5 shot evals I ran appear to be wrong. (the 6.7B and 1.3B evals, for sure.) Not sure what went wrong but rerunning is quick.

I'll pull the ones that may be bad from the repo asap! We'll need to rerun these.

**Comment by StellaAthena** [comment]
Crossposting from the Discord for transparency: we found a bug in our code introduced by a new feature we added between the training and evaluation of the models. It has been corrected but many, if not all, of the evaluations need to be rerun.

**Comment by haileyschoelkopf** [comment]
Yup! I believe all but 1.3B are now corrected, though I need to do another pass through them all and delete bad ones. Should have those soon, the cluster has just been giving me trouble with freezes + not accepting my jobs for some reason.

Also todo:
- [ ] Create `.feather` file + instructions to use for plots with Igor's code
- [ ] Rename `lambada` task to `lambada_openai` everywhere?

**Comment by haileyschoelkopf** [comment]
All evals in this repo should be correct now, as far as I know!
