### ISSUE TITLE
Inconsistent batch sizes reported in readme

### ISSUE THREAD

**Issue by langosco** [EleutherAI/pythia#39]
Thanks for the amazing work!

In the readme, the table reports some models as being trained with a batch size of 4M, but later on you say
> All models were trained for the equivalent of 143000 steps at a batch size of 2,097,152 tokens

which of these is correct?

(Also, you say that checkpoints are created every 2B tokens - if batch sizes differ between models, does that mean that some models have only 500 training steps between checkpoints?)

**Comment by haileyschoelkopf** [comment]
I'll update the readme to clarify this--"equivalent of 143000" is doing too much work there, it should be more clear!

Yes, in actuality the 350M, 125M, and 1.3B models were trained with 4M token batch size, with instead 500 steps between checkpoints. So the checkpoints are consistent with respect to number of tokens per checkpoint and number of tokens in all of training.

The HF model checkpoints, however, all have checkpoints named consistently, so `step1000` for the 1.3B is the first checkpoint, and so is `step1000` for the 6.7B.

Let me know if this clears things up, or if there's anything else still confusing!

**Comment by langosco** [comment]
This clarifies things, thanks!
