### ISSUE TITLE
Pythia few shot capabilities

### ISSUE THREAD

**Issue by AdirRahamim** [EleutherAI/pythia#56]
Hi, thanks for the amazing work!

I tried to use the Pythia model on a simple few-shot task. I gave it a few examples of sentiment analysis tasks (as shown in this example on GPT-J: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/GPT-J-6B/Inference_with_GPT_J_6B.ipynb which successfully solves this), and it seems like it even did not understand the job (generates unrelated tokens). 
Is there a reason for Pythia's failure on this simple task, compared to GPT-J's success (although having twice the number of parameters)?

**Comment by haileyschoelkopf** [comment]
Hi! Can you provide a link to a colab containing the exact code that loads and fails to run Pythia models so that I can attempt to replicate your error?

Additionally, what Pythia model + size are you running?

**Comment by AdirRahamim** [comment]
Hi, here is a Colab notebook with the same code I used: https://colab.research.google.com/drive/1H-o6l8HWzwMu-3rioMNsvE88QzOBMCrZ?usp=sharing

In the code, you can see I tried several models: Pythia 2.7b/6.7b/13b and GPT-J. The only one succeeded in this few-shot sentiment analysis task is the GPT-J model.
Thanks!

**Comment by StellaAthena** [comment]
When I change the prompt to
```
prompt = """
Sentence: This movie is very nice.
Sentiment: positive

Sentence: I hated this movie, it sucks.
Sentiment: negative

Sentence: This movie was actually pretty funny.
Sentiment: positive

Sentence: This movie could have been better.
Sentiment:"""
```
I get reasonable results for all Pythia models. I'm not sure why it doesn't like the separator `#####`, but the only substantial difference with GPT-J-6B is the tokenizer so that's probably the culprit?

**Comment by AdirRahamim** [comment]
Hi, I just tried it again with the updated prompt and I still get unrelated tokens to be generated, are you sure this worked for you?
