### ISSUE TITLE
Generation issues when using KoboldAI

### ISSUE THREAD

**Issue by candymint23** [EleutherAI/pythia#59]
Hi there, I only used Pythia with KoboldAI, particularly 13B and 13B deduped (or maybe 12B due to the rename) and I'm having generation issues. Since I already have a thread on this on KoboldAI, and my post there is already substantial I think, I'm just gonna link it here. https://github.com/ebolam/KoboldAI/issues/312. I'm also gonna attach a pic with one of the issues, particularly spacing issue.
![209335571-43c5da4a-b695-47d7-a2f2-470aba0c8334](https://user-images.githubusercontent.com/113113106/213962557-d1991752-62f4-47ca-a216-1628d2ca082b.png)

**Comment by StellaAthena** [comment]
This is really something you should talk to KoboldAI about, not us. It’s likely a post-processing error on their part.
