### ISSUE TITLE
How was deduplication done?

### ISSUE THREAD

**Issue by theblackcat102** [EleutherAI/pythia#75]
Specifically what method or library does the deduplication of the Pile carried out?

I have search previous issues and this repo and see no other mention of the methodology for deduplication.

**Comment by haileyschoelkopf** [comment]
Hi! More detail will be included in the paper that we hope to upload soon, apologies that this is missing from the repository.

This deduplicated copy of the dataset was created using the code from https://github.com/google-research/deduplicate-text-datasets with MinhashLSH and Jaccard similarity thresholded at 0.87, I believe. Let me know if you have further questions, or if this clarifies things!

**Comment by jeffreyywangg** [comment]
Just to follow up on this—is the deduplicated dataset released anywhere (or will it be)? I'm working on some experiments where I'd really love to have access to a model with an evaluation set that has little or no known contamination with the training. I saw in the original Pile paper that some effort was made in that direction, but I assume the deduped data for Pythia is better?
