### ISSUE TITLE
Ordering of deduplicated datasets?

### ISSUE THREAD

**Issue by zplizzi** [EleutherAI/pythia#76]
I just wanted to confirm that the 3 versions you have of the deduplicated data have the same data ordering?
- https://huggingface.co/datasets/EleutherAI/pythia_deduped_pile_idxmaps (tokenized + sharded)
- https://huggingface.co/datasets/EleutherAI/the_pile_deduplicated (jsonl)
- https://huggingface.co/datasets/EleutherAI/raw_deduplicated_pile (raw, parquet)

I was hoping to use the `jsonl` one but wanted to ensure it will accurately replicate the data ordering in your tokenized dataset that you used for training.

**Comment by zplizzi** [comment]
Thank you!

**Comment by stabilize-ai** [comment]
going from @zplizzi 's original message, do the 2nd and 3rd links below contain the same examples as the ones used for pythia training and in the same order ?


* https://huggingface.co/datasets/EleutherAI/pythia_deduped_pile_idxmaps (tokenized + sharded)
* https://huggingface.co/datasets/EleutherAI/the_pile_deduplicated (jsonl)
* https://huggingface.co/datasets/EleutherAI/raw_deduplicated_pile (raw, parquet)

**Comment by haileyschoelkopf** [comment]
The 2nd and 3rd links do not. They theoretically do contain the same data *if you run prepare_data.py on the 2nd link*, but due to multiprocessing weirdness I can't guarantee the shuffle would end up the same, which is why we supply the first link
