### ISSUE TITLE
Mistake in readme

### ISSUE THREAD

**Issue by zplizzi** [EleutherAI/pythia#81]
In the readme it says

> To download and use the deduplicated Pile training data, run:
> 
> ```
> git lfs clone https://huggingface.co/datasets/EleutherAI/pythia_pile_idxmaps
> 
> python utils/unshard_memmap.py --input_file ./pythia_pile_idxmaps/pile_0.87_deduped_text_document-00000-of-00082.bin --num_shards 83 --output_dir ./pythia_pile_idxmaps/```

But it should actually point to `EleutherAI/pythia_deduped_pile_idxmaps`.

**Comment by haileyschoelkopf** [comment]
Thanks for raising :) ! resolved in latest readme update.
