### ISSUE TITLE
Pythia 6.9B Model Missing Checkpoint

### ISSUE THREAD

**Issue by chujiezheng** [EleutherAI/pythia#94]
Thanks for your great work in releasing Pythia. I found the Pythia 6.9B model does not have a **step26000** checkpoint in huggingface (https://huggingface.co/EleutherAI/pythia-6.9b/tree/main). Could you upload it?

**Comment by haileyschoelkopf** [comment]
Of course! I've uploaded that checkpoint. Sorry about the error, must've had a connection issue when I was uploading that one! I skimmed through and didn't notice any missing branches for 6.9b after a quick check.
